/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package again;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author NGUYEN DUC CUONG
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jfFullname = new javax.swing.JTextField();
        jfUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jfPhoneNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jfAddress = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        jfPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jfPassRetype = new javax.swing.JPasswordField();
        jradioMale = new javax.swing.JRadioButton();
        jradioFeMale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jbSignIN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("again/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("RegisterForm.jLabel1.text")); // NOI18N

        jLabel2.setText(bundle.getString("RegisterForm.jLabel2.text")); // NOI18N

        jLabel3.setText(bundle.getString("RegisterForm.jLabel3.text")); // NOI18N

        jLabel4.setText(bundle.getString("RegisterForm.jLabel4.text")); // NOI18N

        jfFullname.setText(bundle.getString("RegisterForm.jfFullname.text")); // NOI18N

        jfUsername.setText(bundle.getString("RegisterForm.jfUsername.text")); // NOI18N

        jLabel5.setText(bundle.getString("RegisterForm.jLabel5.text")); // NOI18N

        jfPhoneNumber.setText(bundle.getString("RegisterForm.jfPhoneNumber.text")); // NOI18N

        jLabel7.setText(bundle.getString("RegisterForm.jLabel7.text")); // NOI18N

        jfAddress.setColumns(20);
        jfAddress.setRows(5);
        jScrollPane1.setViewportView(jfAddress);

        btnSubmit.setText(bundle.getString("RegisterForm.btnSubmit.text")); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jfPassword.setText(bundle.getString("RegisterForm.jfPassword.text")); // NOI18N

        jLabel8.setText(bundle.getString("RegisterForm.jLabel8.text")); // NOI18N

        jfPassRetype.setText(bundle.getString("RegisterForm.jfPassRetype.text")); // NOI18N
        jfPassRetype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfPassRetypeActionPerformed(evt);
            }
        });

        buttonGroup1.add(jradioMale);
        jradioMale.setText(bundle.getString("RegisterForm.jradioMale.text")); // NOI18N

        buttonGroup1.add(jradioFeMale);
        jradioFeMale.setText(bundle.getString("RegisterForm.jradioFeMale.text")); // NOI18N

        jLabel9.setText(bundle.getString("RegisterForm.jLabel9.text")); // NOI18N

        jbSignIN.setText(bundle.getString("RegisterForm.jbSignIN.text")); // NOI18N
        jbSignIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSignIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSignINMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(jLabel1)
                            .addGap(113, 113, 113)
                            .addComponent(jbSignIN))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jfUsername)
                                    .addComponent(jfPassword)
                                    .addComponent(jfPassRetype)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jfFullname))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(jradioFeMale, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jradioMale, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbSignIN)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jfFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jfPassRetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradioMale)
                    .addComponent(jradioFeMale)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSubmit)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfPassRetypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfPassRetypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfPassRetypeActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (jfFullname.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Họ tên không được rỗng");
                jfFullname.requestFocus();
                return;
            } else if (jfUsername.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Username không được rỗng");
                jfFullname.requestFocus();
                return;
            } else if (jfPassword.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Mật khẩu không được rỗng");
                jfFullname.requestFocus();
                return;
            } else 
                if (jfPhoneNumber.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "SDT không được rỗng");
                jfFullname.requestFocus();
                return;
            }else 
                if (jfAddress.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Địa chỉ không được để rỗng");
                jfFullname.requestFocus();
                return;
            }
        
        
            try {
            Connection connection = DBConnection.getConnection();
            String sql = "INSERT INTO dbo.[users](username,passwords,fullname,phonenumber,addresss,gender)" +  "VALUES(?,?,?,?,?,?)";
            
            PreparedStatement ps = connection.prepareStatement(sql);
            ps.setString(3,jfFullname.getText());
            ps.setNString(1,jfUsername.getText());
            ps.setString(2, jfPassword.getText());
            ps.setString(4, jfPhoneNumber.getText());
            ps.setString(5, jfAddress.getText());
            if(jradioMale.isSelected()){
               ps.setBoolean(6, jradioMale.isSelected());
            }
            else{
                ps.setBoolean(6, false);
            }
            ps.executeUpdate();
           
            DBConnection.closeConnection(connection);
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        JOptionPane.showMessageDialog(this, "Register successfully !");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jbSignINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSignINMouseClicked
        // TODO add your handling code here:
        SignInForm sg = new SignInForm();
        sg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbSignINMouseClicked

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbSignIN;
    private javax.swing.JTextArea jfAddress;
    private javax.swing.JTextField jfFullname;
    private javax.swing.JPasswordField jfPassRetype;
    private javax.swing.JPasswordField jfPassword;
    private javax.swing.JTextField jfPhoneNumber;
    private javax.swing.JTextField jfUsername;
    private javax.swing.JRadioButton jradioFeMale;
    private javax.swing.JRadioButton jradioMale;
    // End of variables declaration//GEN-END:variables
}
